//
//  AWSGoogleIdentityProfile.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.18
//
//

import AWSMobileHubHelper
import GoogleSignIn

let GoogleSignInProviderProfileImageDimension: UInt = 150

class GoogleIdentityProfile : AWSIdentityProfile {
    
    /**
     The URL for profile image of a user.
     */
    public var imageURL: URL?
    /**
     The User Name of a user.
     */
    public var userName: String?
    
    fileprivate var googleProfileAttributes : [String : Any]
    
    init() {
        googleProfileAttributes = [String: Any]()
    }
    
    static let _sharedInstance = GoogleIdentityProfile()
    
    /*
     The shared instance for the profile provider.
     */
    static func sharedInstance() -> AWSIdentityProfile {
        return _sharedInstance
    }
    
    /**
     Fetches custom stored profile attribute using specified key.
     */
    func getAttributeForKey(_ key: String) -> Any? {
        return googleProfileAttributes[key]
    }
    
    /**
     Stores custom values using specified key.
     */
    func setProfileAttribute(_ value: Any, forKey key: String) {
        googleProfileAttributes[key] = value
    }
    
    /**
     Fetches the entire identity profile attributes map.
     */
    func getAttributesMap() -> [String : Any] {
        return googleProfileAttributes
    }
    
    /**
     Clears the current profile information.
     */
    func clear() {
        googleProfileAttributes = [String: Any]()
    }
    
    /**
     Loads the profile information for current signed-in user.
     */
    func load() {
        let googleUser = GIDSignIn.sharedInstance().currentUser
        self.userName = googleUser?.profile.name
        self.imageURL = googleUser?.profile.imageURL(withDimension: GoogleSignInProviderProfileImageDimension)
        // Set any additional proflie attributes here. This method is called after a user signs in with a provider.
    }
    
}
